In [1]:
from datetime import datetime, timedelta

target_date = '2026-03-06'

In [ ]:
API_KEY = "BUe3s2QFD6Amkdt1F6t6sRyKBMAfk9ruS1HFvYQ1r8np"
SECRET_KEY = "AoeSQjaLEtquhrtsjNGZRbTVzXSVKCJCPy8Afn3oaSSU"
import shioaji as sj
import pandas as pd
from datetime import datetime, timedelta
import time
from tqdm import tqdm
import os

if globals().get("global_api", None) is None:
    global_api = sj.Shioaji(simulation=True)
    global_api.login(
        api_key=API_KEY ,
        secret_key=SECRET_KEY ,
        fetch_contract=True
    )

2026-03-07 22:24:09.381 | WARNING  | importlib._bootstrap:_call_with_frames_removed:241 - Optional: pip install shioaji[speed] or uv add shioaji --extra speed for better performance.

Response Code: 0 | Event Code: 0 | Info: host '210.59.255.161:80', hostname '210.59.255.161:80' IP 210.59.255.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session up

Response Code: 200 | Event Code: 16 | Info: APISUB/V1/SYS/CONTRACT | Event: Subscribe or Unsubscribe ok

In [ ]:
# global_api.logout()
# del global_api

In [3]:
from src.config import RAM_PATH
import os
import pandas as pd
from src.factor_engine.engine import FactorEngine
if globals().get("engine", None) is None:
    engine = FactorEngine(
        qlib_data_path=RAM_PATH,
        instrument="all",
        start_time='2026-01-01',
        end_time=target_date,
        device="cpu",               # 支援 "cpu" / "cuda:0" 字串或 torch.device
        max_backtrack_days=0,
        max_future_days=0,
        adjust_factor = 'back'
    )
    df_tradable = engine.load_raw_df("$is_tradable")
    tej_df = engine.load_raw_df(['$open' , '$high' , '$low' , '$close' , '$volume' , '$is_tradable'])

data path: /dev/shm/qlib_ram

[137451:MainThread](2026-03-07 22:24:14,621) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[137451:MainThread](2026-03-07 22:24:15,008) INFO - qlib.Initialization - [__init__.py:82] - qlib successfully initialized based on client settings.
[137451:MainThread](2026-03-07 22:24:15,009) INFO - qlib.Initialization - [__init__.py:84] - data_path={'__DEFAULT_FREQ': PosixPath('/dev/shm/qlib_ram')}

[FactorEngine] Loading data: instrument=all, period=[2026-01-01, 2026-03-06], device=cpu
[FactorEngine] Data loaded: 38 days, 1928 stocks, 10 features, tensor shape=(38, 10, 1928)

#### 獲取當天成交量不為0的所有數據 ，這裡的is_tradable 可能有誤 暫時不刪

In [19]:
# 要檢查這些欄位有沒有 NaN
fields_to_check = ['$open', '$high', '$low', '$close', '$volume']

tej_df_on_targetdate = tej_df.loc[target_date]

# 找出這些欄位哪些 row 有 NaN
mask_has_na = tej_df_on_targetdate[fields_to_check].isna().any(axis=1)
na_rows = tej_df_on_targetdate[mask_has_na]
not_na_rows = tej_df_on_targetdate[~mask_has_na]

print("=== 有 NaN 欄位的紀錄 ===")
display(na_rows)

print("\n=== 沒有 NaN 欄位的紀錄 ===")
display(not_na_rows)
# 再篩掉成交量為0的股票
not_na_nonzero_volume = not_na_rows[not_na_rows['$volume'] != 0]
print("\n=== 沒有 NaN 且成交量不為0的紀錄 ===")
display(not_na_nonzero_volume)

=== 有 NaN 欄位的紀錄 ===

Empty DataFrame
Columns: [$open, $high, $low, $close, $volume, $is_tradable]
Index: []

=== 沒有 NaN 欄位的紀錄 ===

,$open,$high,$low,$close,$volume,$is_tradable
instrument,,,,,,
1101,24.650000,25.250000,24.549999,25.150000,19804.0,1.0
1102,34.299999,34.700001,34.150002,34.450001,6976.0,1.0
1103,13.600000,13.850000,13.500000,13.800000,251.0,1.0
1104,28.850000,29.200001,28.700001,28.900000,656.0,1.0
1108,15.050000,15.150000,15.000000,15.100000,241.0,1.0
...,...,...,...,...,...,...
9951,53.700001,54.099998,53.700001,54.099998,52.0,1.0
9955,34.200001,34.599998,33.799999,34.000000,793.0,1.0
9958,121.000000,124.500000,120.500000,123.500000,821.0,1.0
9960,22.150000,22.600000,22.049999,22.600000,12.0,1.0
9962,11.300000,11.550000,11.300000,11.550000,57.0,1.0

=== 沒有 NaN 且成交量不為0的紀錄 ===

,$open,$high,$low,$close,$volume,$is_tradable
instrument,,,,,,
1101,24.650000,25.250000,24.549999,25.150000,19804.0,1.0
1102,34.299999,34.700001,34.150002,34.450001,6976.0,1.0
1103,13.600000,13.850000,13.500000,13.800000,251.0,1.0
1104,28.850000,29.200001,28.700001,28.900000,656.0,1.0
1108,15.050000,15.150000,15.000000,15.100000,241.0,1.0
...,...,...,...,...,...,...
9951,53.700001,54.099998,53.700001,54.099998,52.0,1.0
9955,34.200001,34.599998,33.799999,34.000000,793.0,1.0
9958,121.000000,124.500000,120.500000,123.500000,821.0,1.0
9960,22.150000,22.600000,22.049999,22.600000,12.0,1.0
9962,11.300000,11.550000,11.300000,11.550000,57.0,1.0

In [20]:
not_na_nonzero_volume.reset_index(inplace = True)
instruments = not_na_nonzero_volume['instrument'].unique()
instruments[:5]

array(['1101', '1102', '1103', '1104', '1108'], dtype=object)

In [5]:
from src.utils.RateLimiter import RateLimiter, retry_on_not_ready
one_min_data_folder = '/home/newt/quant_project/1min_data'

In [6]:
rate_limiter_shioaji = RateLimiter(max_requests=45, time_window=5)
@retry_on_not_ready(max_retries=3, delay=2, rate_limiter=rate_limiter_shioaji)
def fetch_kbars_with_retry_shioaji(api, code, start_date, end_date):
    """帶重試機制和速率限制的 kbars 請求"""    
    kbars = api.kbars(
        contract=api.Contracts.Stocks[code],
        start=start_date,
        end=end_date,
    )
    return kbars

### 從永豐證券下載分K

In [7]:

target_date_obj = datetime.strptime(target_date, '%Y-%m-%d').date()
next_date_obj = target_date_obj + timedelta(days=1)
next_date_str = next_date_obj.strftime('%Y-%m-%d')
next_date_str

'2026-03-07'

In [22]:
from tqdm import tqdm
fail_task = []
result_df_list =[]
no_trade_record = []
instruments_copy = instruments.tolist().copy()
if len(instruments_copy) > 0 :
    with tqdm(total=len(instruments_copy), desc=f"日期: {target_date}", unit="筆") as pbar:
        while len(instruments_copy) > 0 :
            code = instruments_copy.pop(0)
            try:

                kbars = fetch_kbars_with_retry_shioaji(
                global_api, 
                code, 
                target_date,
                next_date_str
                )
                df = pd.DataFrame({**kbars})
                df.ts = pd.to_datetime(df.ts)
                df['code'] = code
                if df.empty:
                    no_trade_record.append(code)
                result_df_list.append(df)
            except Exception as e :
                if "'NoneType' object has no attribute 'dict'" in str(e):
                    fail_task.append(code)
                else:
                    print(e)
            finally :
                pbar.update(1)
df_result = pd.concat(result_df_list)
no_trade_record

日期: 2026-03-06:  57%|█████▋    | 1085/1907 [03:45<20:13,  1.48s/筆]

Topic: api/v1/data/kbars, Corr: c1078, Client: PYAPI/B123243407/0307/142410/293994/140.119.145.12, payload: {'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NzI4OTM0NTAsImV4cCI6MTc3Mjk3OTg1MCwic2ltdWxhdGlvbiI6dHJ1ZSwicGVyc29uX2lkIjoiQjEyMzI0MzQwNyIsInZlcnNpb24iOiIxLjMuMSIsInAycCI6IiNQMlAvdjpiY3NvbGFjZTAxL09yeWZrcXFtL1BZQVBJL0IxMjMyNDM0MDcvMDMwNy8xNDI0MTAvMjkzOTk0LzE0MC4xMTkuMTQ1LjEyLyMiLCJpcCI6IjE0MC4xMTkuMTQ1LjEyIiwicGVybWlzc2lvbnMiOlsiRGF0YSIsIlBvcnRmb2xpbyIsIlRyYWRlIl0sImxldmVsIjoxLCJjYV9yZXF1aXJlZCI6dHJ1ZX0.AwdmjPzNApmDLD_liasdZR-_WTY2R0NtA_QRlXXvn3c', 'contract': {'security_type': 'STK', 'exchange': 'TSE', 'code': '4976', 'symbol': 'TSE4976', 'name': '佳凌', 'category': '26', 'currency': 'TWD', 'delivery_month': '', 'delivery_date': '', 'strike_price': 0, 'option_right': '', 'underlying_kind': '', 'underlying_code': '', 'unit': 1000, 'multiplier': 0, 'limit_up': 33.1, 'limit_down': 27.1, 'reference': 30.1, 'update_date': '2026/03/06', 'margin_trading_balance': 310, 'short_selling_balance': 35, 'day_trade': 'Yes', 'target_code': ''}, 'start': '2026-03-06', 'end': '2026-03-07'}

日期: 2026-03-06: 100%|██████████| 1907/1907 [05:52<00:00,  5.41筆/s]

[]

In [23]:
len(result_df_list)

1906

In [29]:
global_api.usage().remaining_bytes /1024 /1024

2021.3155193328857

In [ ]:
# code = '4976'
# print(target_date)
# print(next_date_str)
# kbars = fetch_kbars_with_retry_shioaji(
#     global_api, 
#     code, 
#     target_date ,
#     next_date_str 
# )
# df = pd.DataFrame({**kbars})
# df.ts = pd.to_datetime(df.ts)
# df['code'] = code
# df.head()

2026-03-06
2026-03-07

                   ts   Open   High    Low  Close  Volume    Amount  code
0 2026-03-06 09:01:00  30.10  30.10  29.90  29.90       9  270000.0  4976
1 2026-03-06 09:04:00  29.75  29.75  29.75  29.75       1   29750.0  4976
2 2026-03-06 09:06:00  29.75  29.75  29.75  29.75       2   59500.0  4976
3 2026-03-06 09:09:00  29.85  29.85  29.75  29.75       2   59600.0  4976
4 2026-03-06 09:10:00  29.75  29.75  29.75  29.75       1   29750.0  4976

In [ ]:
# result_df_list.append(df)
# df_result = pd.concat(result_df_list)

### 從富果下載分K

In [30]:
from fugle_marketdata import RestClient

fugle_client = RestClient(api_key = 'NWQ3YjUyMzYtYmViYS00NWU1LTgwYjMtZjBiZTk1NzQyOWY2IDNiMjJkODVhLTY3ZGYtNDg0My1hMjM3LTFhYjliN2E2M2NkNQ==')  # 輸入您的 API key
fugle_stock = fugle_client.stock  # Stock REST API client

In [36]:
if globals().get("fugle_exist_codes", None) is None:
    fugle_exist_codes = []
fugle_exist_codes[:5]

[]

In [37]:
import pandas as pd
import os
import time
fail_task_fugle = []
result_df_list_fugle =[]
no_trade_record_fugle = []
instruments_copy = instruments.copy()
interval = 1
# for chunk in tqdm(chunks, desc=f"日期: {target_date}", unit="次任務") :
    #start = time.time()
for code in tqdm(instruments_copy, desc=f"日期: {target_date}", unit="筆"):
    if code in fugle_exist_codes:
        continue
    else:
        try:
            df_raw =fugle_stock.historical.candles(**{
                "symbol": code,
                "timeframe" :"1" ,
                "fields": "open,high,low,close,volume"})

            df = pd.DataFrame(df_raw['data'])
            if not pd.api.types.is_datetime64_any_dtype(df['date']):
                df['date'] = pd.to_datetime(df['date'])

            # Filter the DataFrame by matching year, month, and day
            df['code'] = code
            if df.empty:
                no_trade_record_fugle.append(code)
            else : 
                result_df_list_fugle.append(df)
                fugle_exist_codes.append(code)

        #print(f"DataFrame saved to {file_path}")
        except Exception as e :
            print(f'code {code} 發生錯誤 {e}')
            fail_task_fugle.append(code)
        finally:
            time.sleep(interval)
    # end = time.time()
    # diff = end - start
    # if diff <  interval:
    #     print(f'開始休息{interval-diff + 1 :.2f}秒')
    #     time.sleep(interval-diff + 1)
df_result_fugle = pd.concat(result_df_list_fugle)

日期: 2026-03-06:  76%|███████▌  | 1453/1907 [27:25<1:16:27, 10.11s/筆]

code 6585 發生錯誤 [Fugle API Error] HTTP 502
URL: https://api.fugle.tw/marketdata/v1.0/stock/historical/candles/6585?timeframe=1&fields=open%2Chigh%2Clow%2Cclose%2Cvolume
Status: 502
Params: {'timeframe': '1', 'fields': 'open,high,low,close,volume'}
Response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
...

日期: 2026-03-06: 100%|██████████| 1907/1907 [35:41<00:00,  1.12s/筆]

In [38]:
len(result_df_list_fugle)

1906

In [ ]:
df_result_fugle['date'] = df_result_fugle['date'].dt.tz_localize(None)
df_result_fugle = df_result_fugle.set_index(['date', 'code'])
df_result = df_result.set_index(['ts', 'code'])

In [96]:
# 篩出 code = 1101，並依 date 排序
df_1101_fugle = df_result_fugle.xs('1101', level='code').sort_index(level='date')
df_1101_ = df_result.xs('1101', level='code').sort_index(level='date').drop(columns=['Amount'])
from datetime import time, timedelta

t_start = time(9, 0, 0)
t_end = time(13, 27, 0)
idx = df_1101_fugle.index
mask = (idx.time >= t_start) & (idx.time <= t_end)
df_1101_fugle.index = idx.where(~mask, idx + timedelta(minutes=1))

display(df_1101_fugle.head())
display(df_1101_.head())

                      Open   High    Low  Close  Volume
date
2026-03-04 09:01:00  25.40  25.45  25.25  25.25    1310
2026-03-04 09:02:00  25.25  25.30  25.15  25.20    1686
2026-03-04 09:03:00  25.15  25.30  25.15  25.25     714
2026-03-04 09:04:00  25.25  25.25  25.20  25.20     312
2026-03-04 09:05:00  25.25  25.25  25.15  25.15     848

                      Open   High    Low  Close  Volume
date
2026-03-04 09:01:00  25.40  25.45  25.25  25.25  1310.0
2026-03-04 09:02:00  25.25  25.30  25.15  25.20  1686.0
2026-03-04 09:03:00  25.15  25.30  25.15  25.25   714.0
2026-03-04 09:04:00  25.25  25.25  25.20  25.20   312.0
2026-03-04 09:05:00  25.25  25.25  25.15  25.15   848.0

In [100]:
# 1. 統一欄位名稱（富果小寫 → 大寫，方便對齊）
df_1101_fugle = df_1101_fugle.rename(columns={
    'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close' ,'volume': 'Volume'})

# 2. 只取要比較的欄位（df_1101_ 若有 Amount 就不納入比較）
cols = ['Open', 'High', 'Low', 'Close' , 'Volume']
left = df_1101_fugle[cols]
right = df_1101_[cols]

# 3. 用 index (date) 對齊：只保留兩邊都有的時間點
common_idx = left.index.intersection(right.index)
left_aligned = left.loc[common_idx].sort_index()
right_aligned = right.loc[common_idx].sort_index()

# 4. 比較是否一樣（浮點數先 round 再比，避免誤差）
import numpy as np
tol = 1e-9
numeric_eq = np.isclose(left_aligned, right_aligned, rtol=0, atol=tol, equal_nan=True)
# 或整數/小數位一致即可： left_aligned.round(2) == right_aligned.round(2)

print('依 date 對齊後的筆數:', len(common_idx))
print('各欄位完全一致筆數:', numeric_eq.sum())
print('是否全部一致:', numeric_eq.all().all())

# 5. 若有差異，看哪裡

依 date 對齊後的筆數: 265
各欄位完全一致筆數: 1319
是否全部一致: False

In [101]:
# 假設 left_aligned、right_aligned 已依 date 對齊，cols = ['Open','High','Low','Close','Volume']

import numpy as np

# 數值比較（可改成 round(2) 再 == 若你要忽略小誤差）
tol = 1e-9
diff_mask = ~np.isclose(left_aligned, right_aligned, rtol=0, atol=tol, equal_nan=True)

# 有任一一欄不同的「日期」
rows_with_diff = diff_mask.any(axis=1)
dates_diff = left_aligned.index[rows_with_diff]

print('有差異的 date 數量:', len(dates_diff))
print('有差異的 date 列表:', dates_diff.tolist()[:20], '...' if len(dates_diff) > 20 else '')

# 列出「每個欄位」有幾筆不同
print('\n各欄位有差異的筆數:')
print(diff_mask.sum())

# 只保留有差異的列，並並排顯示兩邊的值
left_diff = left_aligned.loc[rows_with_diff]
right_diff = right_aligned.loc[rows_with_diff]

# 並排：左邊 Fugle、右邊 永豐，方便對照
comparison = left_diff.copy()
comparison.columns = [f'{c}_fugle' for c in comparison.columns]
for c in right_diff.columns:
    comparison[f'{c}_永豐'] = right_diff[c].values

# 只標出「該格有差異」的欄位（可選：用 diff_mask 篩出真正不同的格子）
print('\n有差異的列（Fugle vs 永豐 並排）:')
display(comparison)

# 若只要「差異明細」：每一筆不一致的 (date, 欄位, fugle值, 永豐值)
detail = []
for d in dates_diff:
    for col in cols:
        lv, rv = left_aligned.loc[d, col], right_aligned.loc[d, col]
        if not np.isclose(lv, rv, rtol=0, atol=tol, equal_nan=True):
            detail.append({'date': d, 'column': col, 'fugle': lv, '永豐': rv})
df_detail = pd.DataFrame(detail)
print('\n逐筆差異明細 (date, column, fugle, 永豐):')
display(df_detail)

有差異的 date 數量: 5
有差異的 date 列表: [Timestamp('2026-03-04 09:09:00'), Timestamp('2026-03-04 09:10:00'), Timestamp('2026-03-04 09:17:00'), Timestamp('2026-03-04 09:33:00'), Timestamp('2026-03-04 11:55:00')]

各欄位有差異的筆數:
6

有差異的列（Fugle vs 永豐 並排）:

,Open_fugle,High_fugle,Low_fugle,Close_fugle,Volume_fugle,Open_永豐,High_永豐,Low_永豐,Close_永豐,Volume_永豐
date,,,,,,,,,,
2026-03-04 09:09:00,25.10,25.20,25.05,25.20,1094,25.10,25.20,25.05,25.20,1156.0
2026-03-04 09:10:00,25.15,25.25,25.15,25.20,358,25.15,25.25,25.15,25.20,376.0
2026-03-04 09:17:00,25.10,25.15,25.05,25.10,441,25.10,25.15,25.05,25.10,443.0
2026-03-04 09:33:00,24.85,24.85,24.80,24.85,122,24.85,24.85,24.80,24.85,123.0
2026-03-04 11:55:00,25.00,25.05,25.00,25.05,5,25.05,25.05,25.05,25.05,5.0

逐筆差異明細 (date, column, fugle, 永豐):

                 date  column   fugle       永豐
0 2026-03-04 09:09:00  Volume  1094.0  1156.00
1 2026-03-04 09:10:00  Volume   358.0   376.00
2 2026-03-04 09:17:00  Volume   441.0   443.00
3 2026-03-04 09:33:00  Volume   122.0   123.00
4 2026-03-04 11:55:00    Open    25.0    25.05
5 2026-03-04 11:55:00     Low    25.0    25.05

In [83]:
# 1. 統一 index 名稱（若 df_result 第一層叫 ts）
df_result = df_result.rename_axis(index=['date', 'code'])

# 2. 統一欄位名稱（富果小寫 -> 大寫）
df_result_fugle = df_result_fugle.rename(columns={
    'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'volume': 'Volume'
})

# 3. 只取要比較的欄位
cols = ['Open', 'High', 'Low', 'Close', 'Volume']
common_idx = df_result.index.intersection(df_result_fugle.index)

left = df_result.loc[common_idx, cols]
right = df_result_fugle.loc[common_idx, cols]

# 4. 比較（浮點可先 round 再比，例如小數 2 位）
left_r = left.round(2)
right_r = right.round(2)
diff = left_r != right_r
print('各欄位不相等的筆數：', diff.sum())
print('有差異的 (date, code) 數：', diff.any(axis=1).sum())

各欄位不相等的筆數： Open       89814
High       85211
Low        83804
Close      89909
Volume    143582
dtype: int64
有差異的 (date, code) 數： 150994

In [37]:
df_result.head()

                           Open   High    Low  Close  Volume      Amount
ts                  code
2026-03-03 09:01:00 1101  26.35  26.35  26.25  26.25   917.0  24133100.0
2026-03-03 09:02:00 1101  26.25  26.25  26.25  26.25   171.0   4488750.0
2026-03-03 09:03:00 1101  26.25  26.25  26.20  26.20   138.0   3620050.0
2026-03-03 09:04:00 1101  26.20  26.30  26.20  26.25   232.0   6094350.0
2026-03-03 09:05:00 1101  26.30  26.30  26.25  26.30   144.0   3787050.0

In [ ]:
tej_path = '/home/newt/quant_project/TEJ_processed_data'
df_tej = pd.read_parquet(os.path.join(tej_path, target_date.replace('-', ''), f'{target_date.replace("-", "")}.parquet'))
tej_tradable_instruments = df_tej[df_tej['is_tradable'] == 1]['instrument'].tolist()
tej_tradable_instruments[:5]

In [ ]:
result_codes = df_result['code'].unique().tolist()
result_codes.extend(no_trade_record)
result_codes[:5]

In [ ]:
# 找出哪些 code 在 tej_path 內，但 result_codes 沒有的
codes_in_tej_not_hf = set(tej_tradable_instruments) - set(result_codes)

# 反之：哪些 code 在 result_codes 內，但 tej_path 沒有的
codes_in_hf_not_instr = set(result_codes) - set(tej_tradable_instruments)

print("在 tej_path 內，但 result_codes 沒有的 code：", sorted(codes_in_tej_not_hf))
print(len(codes_in_tej_not_hf))
print("在 result_codes 內，但 tej_path 沒有的 code：", sorted(codes_in_hf_not_instr))
print(len(codes_in_hf_not_instr))

In [ ]:
df = pd.DataFrame({**kbars})
df.ts = pd.to_datetime(df.ts)
df['code'] = code
df.head()